// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtagvcnhbglvdpgjlvtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0YWd2Y25oYmdsdmRwZ2psdnRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzNTc3NjQsImV4cCI6MjA3NjkzMzc2NH0.C4sDLT2ApECNlUmkGvrNmwRk80CE9tHWuBReEWe_gE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});